### ISSUE TITLE
Add snake case support for DotDict wrapper

### ISSUE THREAD

**Issue by Mwyann** [MarshalX/atproto#142]
When using listRecords, if a post is using custom records (like "via" for example), the SDK returns the original dict which is not fully compatible with the proper instance because of the snake/camelCase notation difference on some fields (createdAt, indexedAt, likeCount...).

See original discussion here:
https://bsky.app/profile/mwyann.fr/post/3k757t5scw62l

Maybe other methods are affected too, but it only happened to me with this method anyway.

**Comment by MarshalX** [comment]
Description: all custom records are wrapped using DotDict. But only lexicon legit models will be returned as model instances. Models will be created by converting camel case field names to snake ones. When SDK wraps a custom record using DotDict snake case access is not possible. 

Solution: If the user accesses DotDict by snake case key let's convert this key in runtime and try to fetch the value by camel-cased variant. This also saves access by original camel-cased field names.

**Comment by Mwyann** [comment]
Hi, it's me again...

I've got a case where the camel case conversion is broken, like this:

```
Exception in thread Thread-1 (subscribeNotifications):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yann/bluesky/bluesky-feed-generator/server/likes.py", line 126, in subscribeNotifications
    addLikerPosts(did)
  File "/home/yann/bluesky/bluesky-feed-generator/server/likes.py", line 50, in addLikerPosts
    if 'reply' in record and record.reply and record.reply.parent.uri:
       ^^^^^^^^^^^^^^^^^
  File "/home/yann/bluesky/bluesky-feed-generator/lib/python3.11/site-packages/atproto/xrpc_client/models/dot_dict.py", line 78, in __getitem__
    return self._data.get(_convert_to_opposite_case(item))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yann/bluesky/bluesky-feed-generator/lib/python3.11/site-packages/atproto/xrpc_client/models/dot_dict.py", line 28, in _convert_to_opposite_case
    if _is_snake_case(string):
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yann/bluesky/bluesky-feed-generator/lib/python3.11/site-packages/atproto/xrpc_client/models/dot_dict.py", line 24, in _is_snake_case
    return string == _convert_camel_case_to_snake_case(string)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yann/bluesky/bluesky-feed-generator/lib/python3.11/site-packages/atproto/xrpc_client/models/dot_dict.py", line 14, in _convert_camel_case_to_snake_case
    s = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', string)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'int'
```

The `record` variable on likes.py is as follows when this happens:

```
{
   "text":"Est ce que vous aimez les sondages ? \n\n1?? oui\n2?? non\n3?? ça dépend\n\n? Show results",
   "$type":"app.bsky.feed.post",
   "facets":[
      {
         "index":{
            "byteEnd":50,
            "byteStart":47
         },
         "features":[
            {
               "uri":"https://poll.blue/p/ltfSBx/1",
               "$type":"app.bsky.richtext.facet#link"
            }
         ]
      },
      {
         "index":{
            "byteEnd":62,
            "byteStart":59
         },
         "features":[
            {
               "uri":"https://poll.blue/p/ltfSBx/2",
               "$type":"app.bsky.richtext.facet#link"
            }
         ]
      },
      {
         "index":{
            "byteEnd":82,
            "byteStart":71
         },
         "features":[
            {
               "uri":"https://poll.blue/p/ltfSBx/3",
               "$type":"app.bsky.richtext.facet#link"
            }
         ]
      },
      {
         "index":{
            "byteEnd":101,
            "byteStart":84
         },
         "features":[
            {
               "uri":"https://poll.blue/p/ltfSBx/0",
               "$type":"app.bsky.richtext.facet#link"
            }
         ]
      },
      {
         "index":{
            "byteEnd":50,
            "byteStart":47
         },
         "features":[
            {
               "$type":"app.pollblue.poll.facet#option",
               "number":1
            }
         ]
      },
      {
         "index":{
            "byteEnd":62,
            "byteStart":59
         },
         "features":[
            {
               "$type":"app.pollblue.poll.facet#option",
               "number":2
            }
         ]
      },
      {
         "index":{
            "byteEnd":82,
            "byteStart":71
         },
         "features":[
            {
               "$type":"app.pollblue.poll.facet#option",
               "number":3
            }
         ]
      }
   ],
   "createdAt":"2023-09-20T11:23:14.715Z"
}
```

**Comment by MarshalX** [comment]
>   File "/home/yann/bluesky/bluesky-feed-generator/server/likes.py", line 50, in addLikerPosts
    if 'reply' in record and record.reply and record.reply.parent.uri:
       ^^^^^^^^^^^^^^^^^

ig "in" operator doesn't supported by DotDict fallback

remove `'reply' in record` because `record.reply` is enough?

**Comment by Mwyann** [comment]
I thought it was equivalent for this use case, but I was having a different behavior once without the in operator, I don't remember what happened, maybe it was because of another issue. I removed it for now and it works fine, I'll see if the problem shows up again . Thanks :)
