### ISSUE TITLE
1 validation error for Response

### ISSUE THREAD

**Issue by Linus2punkt0** [MarshalX/atproto#171]
Since around midnight last night I have started getting the following error when using atproto:

```
Traceback (most recent call last):
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 87, in _get_or_create
    return model(**model_data)
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/pydantic/main.py", line 165, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Response
emailConfirmed
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.3/v/extra_forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[PATH REDACTED]", line 15, in <module>
    bsky.login(bsky_handle, bsky_password)
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/client/client.py", line 74, in login
    session = self._get_and_set_session(login, password)
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/client/client.py", line 37, in _get_and_set_session
    session = self.com.atproto.server.create_session(
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/namespaces/sync_ns.py", line 1757, in create_session
    return get_response_model(response, models.ComAtprotoServerCreateSession.Response)
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 98, in get_response_model
    return get_or_create(response.content, model)
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 64, in get_or_create
    raise e
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 57, in get_or_create
    model_instance = _get_or_create(model_data, model, strict=strict)
  File "/[PATH REDACTED]/.local/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 89, in _get_or_create
    raise ModelError(str(e)) from e
atproto.exceptions.ModelError: 1 validation error for Response
emailConfirmed
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.3/v/extra_forbidden
```

Since no changes have been made on my end, and I haven't downloaded a new version of atproto, I assume something must have changed with the API? Or I'm missing something obvious on my end, also a possibility.

**Comment by MarshalX** [comment]
fixed in v0.0.29; #172
