### ISSUE TITLE
app.bsky.notification.list_notifications method started failing about an hour ago.

### ISSUE THREAD

**Issue by max2pt0** [MarshalX/atproto#201]
Probably related to this change to  bluesky-social / atproto which occurred around the same time: 
https://github.com/bluesky-social/atproto/pull/1959

When this was working a bit over an hour ago the "seen_at" parameter was documented as optional but including it always generated the error message: 'The seenAt parameter is unsupported'. Removing this parameter allowed app.bsky.notification.list_notifications() to work.

Now the same call generates the following error:
```
Traceback (most recent call last):
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 87, in _get_or_create
    return model(**model_data)
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Response
seenAt
  Extra inputs are not permitted [type=extra_forbidden, input_value='2023-12-12T21:40:05.894Z', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/max/zz_dev/projects/p20_bs/main.py", line 54, in <module>
    example_42_appbskynotification_list_notifications()
  File "/home/max/zz_dev/projects/p20_bs/example.py", line 509, in example_42_appbskynotification_list_notifications
    FEED = client.app.bsky.notification.list_notifications({'limit': limit, 'cursor': cursor})
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/atproto/xrpc_client/namespaces/sync_ns.py", line 970, in list_notifications
    return get_response_model(response, models.AppBskyNotificationListNotifications.Response)
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 98, in get_response_model
    return get_or_create(response.content, model)
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 64, in get_or_create
    raise e
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 57, in get_or_create
    model_instance = _get_or_create(model_data, model, strict=strict)
  File "/home/max/.local/share/virtualenvs/p20_bs-CytYnhbM/lib/python3.10/site-packages/atproto/xrpc_client/models/utils.py", line 89, in _get_or_create
    raise ModelError(str(e)) from e
atproto.exceptions.ModelError: 1 validation error for Response
seenAt
  Extra inputs are not permitted [type=extra_forbidden, input_value='2023-12-12T21:40:05.894Z', input_type=str]
    For further information visit https://errors.pydantic.dev/2.5/v/extra_forbidden
```

**Comment by max2pt0** [comment]
For a temporary fix I added the following to a local version of xrpc_client/models/app/bsky/notification/list_notifications.py

After line 39: 
cursor: t.Optional[str] = None  #: Cursor.

Added: 
seenAt: t.Optional[str] = None

**Comment by MarshalX** [comment]
fixes in v0.0.33 pls upgrade
