### ISSUE TITLE
Strange error when attempting to install as local/interactive package using pip

### ISSUE THREAD

**Issue by Meorge** [MarshalX/atproto#387]
When attempting to install the `atproto` SDK in a Python 3.12.0 venv virtual environment using `pip`, I get a strange error:

```
(.venv) ➜  atproto-install-test python -m pip install -e '/Users/malcolmanderson/Documents/Repositories/atproto' 
Obtaining file:///Users/malcolmanderson/Documents/Repositories/atproto
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "/Users/malcolmanderson/Documents/Repositories/atproto-install-test/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/malcolmanderson/Documents/Repositories/atproto-install-test/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/malcolmanderson/Documents/Repositories/atproto-install-test/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 42, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/poetry_dynamic_versioning/patch.py", line 26, in alt_poetry_create
          name = _get_and_apply_version(
                 ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/poetry_dynamic_versioning/__init__.py", line 681, in _get_and_apply_version
          version, instance = _get_version(config, name)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/poetry_dynamic_versioning/__init__.py", line 499, in _get_version
          version = _get_version_from_dunamai(vcs, pattern, config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/poetry_dynamic_versioning/__init__.py", line 462, in _get_version_from_dunamai
          return Version.from_vcs(
                 ^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/dunamai/__init__.py", line 2082, in from_vcs
          return cls._do_vcs_callback(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/dunamai/__init__.py", line 2137, in _do_vcs_callback
          return callback(**kwargs)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/dunamai/__init__.py", line 1182, in from_git
          return cls._fallback(
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/h7/ts4nbz2947v63clk0p32ryzh0000gn/T/pip-build-env-x6bkv9s9/overlay/lib/python3.12/site-packages/dunamai/__init__.py", line 963, in _fallback
          raise RuntimeError("No tags available and fallbacks disabled by strict mode")
      RuntimeError: No tags available and fallbacks disabled by strict mode
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Strangely, doing either
```
python -m pip install atproto
```
or
```
python -m pip install git+https://github.com/MarshalX/atproto.git
```
seems to work just fine, but
```
python -m pip install git+https://github.com/Meorge/atproto.git
```
(i.e., using my fork of the repo) gives the error.

Digging into `pyproject.toml`, I found that by changing `strict = True` to `strict = False` under the section `[tool.poetry-dynamic-versioning]`, I was able to get the editable local install to succeed.

Might anyone have any ideas on how I could get the local editable install to work correctly, without needing to modify `pyproject.toml`?

**Comment by MarshalX** [comment]
The project versioning system uses git tags. Probably when you do a fork it does not copy git tags from the original repository. Create a tag in your fork to fix the problem

**Comment by Meorge** [comment]
Thanks so much - added a tag and it works now!
