### ISSUE TITLE
Not being able to use get_upload_limits

### ISSUE THREAD

**Issue by GuiSaiUwU** [MarshalX/atproto#396]
So I was checking the api docs and found about [getUploadLimits](https://docs.bsky.app/docs/api/app-bsky-video-get-upload-limits), but when I try in code it raises a error 😢, is this an issue with the SDK or the API itself? 

```py
def main() -> None:
    client = Client()
    bot_profile = client.login(getenv('BOT_NAME'), getenv('BOT_PASSWORD'))
    
    print(f"Logged as: {bot_profile.display_name}")
    video_limit = client.app.bsky.video.get_upload_limits()
    print(video_limit.model_dump_json())
```
```
Traceback (most recent call last):
  File "\BskyVideoBot\main.py", line 30, in <module>
    main()
  File "\BskyVideoBot\main.py", line 26, in main
    video_limit = client.app.bsky.video.get_upload_limits()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\namespaces\sync_ns.py", line 3697, in get_upload_limits
    response = self._client.invoke_query(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\client\base.py", line 106, in invoke_query
    return self._invoke(InvokeType.QUERY, url=self._build_url(nsid), params=params, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\client\client.py", line 41, in _invoke
    return super()._invoke(invoke_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\client\base.py", line 121, in _invoke
    return self.request.get(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\request.py", line 158, in get     
    return _parse_response(self._send_request('GET', *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\request.py", line 151, in _send_request
    _handle_request_errors(e)
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\request.py", line 50, in _handle_request_errors
    raise exception
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\request.py", line 149, in _send_request
    return _handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\BskyVideoBot\.venv\Lib\site-packages\atproto_client\request.py", line 79, in _handle_response
    raise exceptions.RequestException(error_response)
atproto_client.exceptions.RequestException: Response(success=False, status_code=404, content=XrpcError(error='XRPCNotSupported', message='XRPCNotSupported'), headers={'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '3000', 'ratelimit-remaining': '2998', 'ratelimit-reset': '1726210087', 'ratelimit-policy': '3000;w=300', 'cache-control': 'private', 'vary': 'Authorization, Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'content-length': '57', 'etag': 'W/"39-WI+yvBMnUIXHN9mmjmhFBSzX9h4"', 'date': 'Fri, 13 Sep 2024 06:43:07 GMT', 'keep-alive': 'timeout=90', 'strict-transport-security': 'max-age=63072000'}) 
```

**Comment by MarshalX** [comment]
This is server side error. Because we need to perform this request to video server instead of PDS as default client behaviour
