### ISSUE TITLE
Cannot login on my PDS with domain username

### ISSUE THREAD

**Issue by mike-cuche** [MarshalX/atproto#425]
Hello, I set up a PDS (pds.cuche.cc) , created my account and set its username as my domain (@cuche.cc)
When I try to log in I got these errors:
```
>>> from atproto import Client, client_utils
>>> client = Client()
>>> profile = client.login("cuche.cc","$password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/client/client.py", line 105, in login
    session = self._get_and_set_session(login, password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/client/client.py", line 48, in _get_and_set_session
    session = self.com.atproto.server.create_session(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/namespaces/sync_ns.py", line 5427, in create_session
    response = self._client.invoke_procedure(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/client/base.py", line 115, in invoke_procedure
    return self._invoke(InvokeType.PROCEDURE, url=self._build_url(nsid), params=params, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/client/client.py", line 41, in _invoke
    return super()._invoke(invoke_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/client/base.py", line 122, in _invoke
    return self.request.post(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/request.py", line 165, in post
    return _parse_response(self._send_request('POST', *args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/request.py", line 155, in _send_request
    _handle_request_errors(e)
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/request.py", line 54, in _handle_request_errors
    raise exception
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/request.py", line 153, in _send_request
    return _handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Progetti/crossposter/lib/python3.12/site-packages/atproto_client/request.py", line 77, in _handle_response
    raise exceptions.UnauthorizedError(error_response)
atproto_client.exceptions.UnauthorizedError: Response(success=False, status_code=401, content=XrpcError(error='AuthenticationRequired', message='Invalid identifier or password'), headers={'date': 'Sat, 09 Nov 2024 13:03:47 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '77', 'connection': 'keep-alive', 'x-powered-by': 'Express', 'access-control-allow-origin': '*', 'ratelimit-limit': '30', 'ratelimit-remaining': '29', 'ratelimit-reset': '1731157727', 'ratelimit-policy': '30;w=300', 'etag': 'W/"4d-98r3hvgolnybv7tgksQiZbSE7Zg"', 'vary': 'Accept-Encoding'})
>>> 
```
Is this library able to access a PDS when a domain name is set as a username?

**Comment by MarshalX** [comment]
Hi, you should provide URL of your PDS to the constructor of the Client

**Comment by mike-cuche** [comment]
I got it!

Thanks :)
