### ISSUE TITLE
Odd error from pydantic when working with firehose

### ISSUE THREAD

**Issue by jaherron** [MarshalX/atproto#444]
I keep getting exceptions that look like this when trying to parse the firehose.

```
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/home/jaherron/code/python/skyalert/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 101, in _get_or_create
    return model(**model_data)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jaherron/code/python/skyalert/.venv/lib/python3.12/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '3lbdb...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.12/lib/python3.12/multiprocessing/pool.py", line 109, in worker
    initializer(*initargs)
  File "/home/jaherron/code/python/skyalert/skyalert-firehose.py", line 229, in worker_main
    commit = parse_subscribe_repos_message(message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaherron/code/python/skyalert/.venv/lib/python3.12/site-packages/atproto_firehose/firehose.py", line 58, in parse_subscribe_repos_message
    return get_or_create(message.body, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaherron/code/python/skyalert/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 69, in get_or_create
    raise e
  File "/home/jaherron/code/python/skyalert/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 62, in get_or_create
    model_instance = _get_or_create(model_data, model, strict=strict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jaherron/code/python/skyalert/.venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 103, in _get_or_create
    raise ModelError(str(e)) from e
atproto_client.exceptions.ModelError: 1 validation error for Commit
blocks
  Field required [type=missing, input_value={'ops': [], 'rev': '3lbdb...: False, 'tooBig': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

**Comment by MarshalX** [comment]
hi! duplicates https://github.com/MarshalX/atproto/issues/186
