### ISSUE TITLE
Embed Thumbnail Throwing PydanticSerializationError

### ISSUE THREAD

**Issue by graycastle** [MarshalX/atproto#494]
Currently working to create a simple post using a text_builder and an added embed. The code below works perfectly _except_ for when an image is included in the embed:

```
# Create a session
client = Client()
profile = client.login(settings.BLUESKY_USERNAME, settings.BLUESKY_PASSWORD)

# Create a post with multi-line text, a reference to a user, and an embedded link
tb = client_utils.TextBuilder()

tb.text('Post text with user @').mention(user_handle, mention.did).text(' with tag ').tb.tag('#tag','#tag')
  

embed = models.AppBskyEmbedExternal.Main(
    external=models.AppBskyEmbedExternal.External(
        title=entry.name,
        description=entry.excerpt,
        uri='https://www.tinytableindex.com' + entry.get_absolute_url()
    )
)

if entry.image_url:
    response = requests.get(image_url)
    if response.status_code == 200:
        image_blob = response.content
        embed.external.thumb = image_blob

post = client.send_post(tb, embed=embed)
```

I've tried executing a few different ways with adding the embed image, including using a simple local JPEG, grabbing the remote image a few different ways, and any attempt to post an embed with an image results in the PydanticSerializationError below (this is being used in a Django application, so the traceback is from the Django debug):

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/management/admin/post-to-bluesky/

Django Version: 5.1.1
Python Version: 3.12.4
Installed Applications:
['dal',
 'dal_select2',
 'admin_interface',
 'colorfield',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.postgres',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'django.contrib.sitemaps',
 'debug_toolbar',
 'taggit',
 'django_htmx',
 'crispy_forms',
 'crispy_bootstrap5',
 'captcha',
 'markdownx',
 'import_export',
 'django_check_seo',
 'django_json_widget',
 'pages.apps.PagesConfig',
 'entries.apps.EntriesConfig',
 'management.apps.ManagementConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_htmx.middleware.HtmxMiddleware',
 'core.middleware.AppendSlashMiddleware']



Traceback (most recent call last):
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/management/views.py", line 206, in admin_action_post_to_bluesky
    new_entry_post(entry)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/utils/social.py", in new_entry_post

  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/client/client.py", line 160, in send_post
    return self.app.bsky.feed.post.create(repo, record)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/namespaces/sync_ns.py", line 788, in create
    response = self._client.invoke_procedure(
               
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/client/base.py", line 115, in invoke_procedure
    return self._invoke(InvokeType.PROCEDURE, url=self._build_url(nsid), params=params, data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/client/client.py", line 40, in _invoke
    return super()._invoke(invoke_type, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/client/base.py", line 118, in _invoke
    _handle_kwagrs(kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/client/base.py", line 39, in _handle_kwagrs
    kwargs['data'] = get_model_as_json(kwargs['data'])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/atproto_client/models/utils.py", line 131, in get_model_as_json
    return model.model_dump_json(exclude_none=True, by_alias=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/Documents/Lukemade/Projects/Tiny Table/tiny-table/venv/lib/python3.12/site-packages/pydantic/main.py", line 477, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           

Exception Type: PydanticSerializationError at /management/admin/post-to-bluesky/
Exception Value: Error serializing to JSON: invalid utf-8 sequence of 1 bytes from index 0
```

Posting _without_ an embedded image works smoothly as expected.

Curious if anyone else has run into this or if it's a bug in atproto

**Comment by MarshalX** [comment]
Thumb is blob. Not bytes. You should call upload blob at least. Check this example https://github.com/MarshalX/atproto/blob/main/examples/advanced_usage/send_ogp_link_card.py

**Comment by graycastle** [comment]
@MarshalX Thanks for the heads up, that's exactly what I was needing. User error.
